### ISSUE TITLE
Sub settings not included in URL specification

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-a11y#41]
Why aren't sub settings of Universal Access included in the [URL specification](https://docs.google.com/document/d/1N0uqNtVXEFn3cLgNMeN75mP_dpMpCco-7uw5PKow-_Q/edit?usp=sharing)? Url's like:
- universal-access/display
- universal-access/audio
- universal-access/typing
- universal-access/keyboard
- universal-access/pointing
- universal-access/clicking

Implementing this would also enabling searching on these items in the Applications menu, see: https://github.com/elementary/applications-menu/pull/133

**Comment by peteruithoven** [comment]
The System Settings Schema Specification has been moved to the Switchboard wiki:
https://github.com/elementary/switchboard/wiki/System-Settings-Schema-Specification

**Comment by danrabbit** [comment]
The specification is just supposed to be a minimum viable set of URLs that could apply to any desktop environment. I think sub-pages are too implementation specific to make sense here.

We've also recently moved many of these subpages to other pages, so even in elementary these don't all make sense.

I'm going to close this since it seems we can already search for all of the relevant settings here
